source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem 'sassc'
gem "nokogiri", ">= 1.10.4"
gem "kramdown", ">= 2.3.0"
gem "commonmarker"
gem "faraday-retry" 
gem "webrick", "~> 1.7"
gem "csv"
