name: 'Push commit'
on:
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'David Firth'
          git config --global user.email 'DavidFirth@users.noreply.github.com'
          git add report.txt
	  git commit -am "Automated report"
          git push